package:
  name: plotly
  version: "1.3.2"

source:
  git_url: git@github.com:plotly/python-api.git

build:
  number: 1
  script: python setup.py install

requirements:
  build:
    - python
    - setuptools
    - requests
    - six
  run:
    - python
    - setuptools
    - requests
    - six

about:
  home: https://plot.ly
  license: MIT
